export enum StudyBlockComponentType {
  HEADER = "HEADER",
  PARAGRAPH = "PARAGRAPH",
  SHORT_AUDIO = "SHORT_AUDIO",
  LONG_AUDIO = "LONG_AUDIO",
  IMAGE = "IMAGE",
  TEXT_ANSWER = "TEXT_ANSWER",
  TIMER = "TIMER",
  CHECKLIST = "CHECKLIST",
  PRONUNCIATION_ANSWER = "PRONUNCIATION_ANSWER",
  TABLE_FILL = "TABLE_FILL",
  FILL_IN_SENTENCE = "FILL_IN_SENTENCE",
}
